server:
  port: 8082
spring:
  application:
    name: lch-support
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka